import Head from 'next/head'
import Header from '../componennts/Header'
import Nav from '../componennts/Nav'
import Results from '../componennts/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  console.log({results})
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Nav/>
      <Results results={results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const request = await fetch(requests[genre]?.url || requests.fetchTrending.url)
  .then((res) => res.json())

  return{
    props:{
      results: request.results,
    }
  }
}
